### PR TITLE
File::ShareDir::Install fixes and restoration of Perl 5.6 support

### PR DESCRIPTION
**Pull request by kentfredric**
I discovered earlier this morning that File::ShareDir 1.101 degraded the perl support level from 5.005 back to 5.008.

Attached Patch sequence attempts to:
- Restore Perl support back to 5.006
- Tidy up Makefile.PL to avoid the need to depend-on _and_ bundle File::ShareDir::Install
- Import some very minor tweaks to File::ShareDir::Install from its 0.10 release. ( With patches for 5.006 support which will be submitted upstream as soon as ether gets a git copy of the project working )

Toolchain don't see much value in depending on File::ShareDir::Install if you're already bundling it. Seems like you've already paid the price of complexity by bundling it, may as well benefit from bundling it =)

### CODE REVIEW

**Comment by jjatria** [comment]
I just had to add a requirement to File::ShareDir::Install 0.10 on one of my distributions that uses File::ShareDir, just to bring in those fixes.

:+1: to this PR

**Comment by rehsack** [comment]
There is no reason for Perl 5.6 support because of https://github.com/Perl-Toolchain-Gang/toolchain-site/blob/master/lancaster-consensus.md

**Comment by jjatria** [comment]
Oh, I wasn't thinking about the support for 5.6. I meant the fixes that were made in File::ShareDir::Install 0.10. Not having them was causing one of my distributions to have failures on [5.10](http://matrix.cpantesters.org/?dist=Config-AWS%200.03;os=linux;perl=5.10.1;reports=1) and [5.18](http://matrix.cpantesters.org/?dist=Config-AWS%200.03;os=linux;perl=5.18.2;reports=1).

These were fixed when I bumped the requirement to 0.10. I got to this PR when trying to open a ticket to suggest doing the 0.10 requirement on File::ShareDir directly, without knowing it came with a bundled copy.

**Comment by rehsack** [comment]
I can think about fixing it by changing it to auto-bundling the latest version using inc::latest for CPAN releases as I do for List::MoreUtils. Would that fix your issue?

**Comment by jjatria** [comment]
So whenever you make a release, it would ship with the latest version of bundled modules?
If that's the case, that sounds good to me (and I'll make sure to bump my requirement of File::ShareDir to this new version). 👍

**Comment by rehsack** [comment]
Yes, that is the evil idea behind using inc::latest :)

**Comment by rehsack** [comment]
https://st.aticpan.org/source/REHSACK/File-ShareDir-1.104/inc/inc_File-ShareDir-Install/File/ShareDir/Install.pm shows me VERSION 0.11. I think, this can be closed.

@jjatria - 1.104 introduces my above mentioned suggestion ;)

**Pull request closed without merging**
